#!/bin/sh
RC="$HOME/.scripts/conkyrc_right"
FG="#555555"
BG="#151515"
ALIGN="right"
WIDTH="766"
HEIGHT="14"
#FONT="-*-cure-medium-*-*-*-11-*-*-*-*-*-*-*"
#FONT="-*-ProggySmallTT-medium-*-*-*-15-*-*-*-*-*-*-*"
FONT="-*-Terminus-medium-*-*-*-10-*-*-*-*-*-*-*"
XPOS="600" 
YPOS="1"

exec conky -d -c $RC | dzen2 -fg $FG -bg $BG -ta $ALIGN -w $WIDTH -h $HEIGHT -x $XPOS -y $YPOS -fn $FONT &
exit 0
