#!/bin/sh
RC="$HOME/.scripts/conkyrc_left"
FG="#555555"
BG="#151515"
ALIGN="left"
WIDTH="600"
HEIGHT="14"
#FONT="-*-cure-medium-*-*-*-11-*-*-*-*-*-*-*"
#FONT="-*-ProggySmallTT-medium-*-*-*-15-*-*-*-*-*-*-*"
FONT="-*-Terminus-medium-*-*-*-10-*-*-*-*-*-*-*"
XPOS="0" 
YPOS="1"

exec conky -d -c $RC | dzen2 -fg $FG -bg $BG -ta $ALIGN -w $WIDTH -h $HEIGHT -x $XPOS -y $YPOS -fn $FONT &
exit 0
